//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFLabb1Client.MovieOfTheYearServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieOfTheYearServiceReference.MovieYearSoap")]
    public interface MovieYearSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MovieOfTheYear", ReplyAction="*")]
        WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearResponse MovieOfTheYear(WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MovieOfTheYear", ReplyAction="*")]
        System.Threading.Tasks.Task<WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearResponse> MovieOfTheYearAsync(WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MovieOfTheYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MovieOfTheYear", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequestBody Body;
        
        public MovieOfTheYearRequest() {
        }
        
        public MovieOfTheYearRequest(WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MovieOfTheYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public MovieOfTheYearRequestBody() {
        }
        
        public MovieOfTheYearRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MovieOfTheYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MovieOfTheYearResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearResponseBody Body;
        
        public MovieOfTheYearResponse() {
        }
        
        public MovieOfTheYearResponse(WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MovieOfTheYearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MovieOfTheYearResult;
        
        public MovieOfTheYearResponseBody() {
        }
        
        public MovieOfTheYearResponseBody(string MovieOfTheYearResult) {
            this.MovieOfTheYearResult = MovieOfTheYearResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MovieYearSoapChannel : WCFLabb1Client.MovieOfTheYearServiceReference.MovieYearSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieYearSoapClient : System.ServiceModel.ClientBase<WCFLabb1Client.MovieOfTheYearServiceReference.MovieYearSoap>, WCFLabb1Client.MovieOfTheYearServiceReference.MovieYearSoap {
        
        public MovieYearSoapClient() {
        }
        
        public MovieYearSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieYearSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieYearSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieYearSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearResponse WCFLabb1Client.MovieOfTheYearServiceReference.MovieYearSoap.MovieOfTheYear(WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequest request) {
            return base.Channel.MovieOfTheYear(request);
        }
        
        public string MovieOfTheYear(string input) {
            WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequest inValue = new WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequest();
            inValue.Body = new WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequestBody();
            inValue.Body.input = input;
            WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearResponse retVal = ((WCFLabb1Client.MovieOfTheYearServiceReference.MovieYearSoap)(this)).MovieOfTheYear(inValue);
            return retVal.Body.MovieOfTheYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearResponse> WCFLabb1Client.MovieOfTheYearServiceReference.MovieYearSoap.MovieOfTheYearAsync(WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequest request) {
            return base.Channel.MovieOfTheYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearResponse> MovieOfTheYearAsync(string input) {
            WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequest inValue = new WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequest();
            inValue.Body = new WCFLabb1Client.MovieOfTheYearServiceReference.MovieOfTheYearRequestBody();
            inValue.Body.input = input;
            return ((WCFLabb1Client.MovieOfTheYearServiceReference.MovieYearSoap)(this)).MovieOfTheYearAsync(inValue);
        }
    }
}
