//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFLabb1Client.Subtract2NumbersReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Subtract2NumbersReference.Subtract2NumbersSoap")]
    public interface Subtract2NumbersSoap {
        
        // CODEGEN: Generating message contract since element name x from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractTwoNumbers", ReplyAction="*")]
        WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersResponse SubtractTwoNumbers(WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersResponse> SubtractTwoNumbersAsync(WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractTwoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractTwoNumbers", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequestBody Body;
        
        public SubtractTwoNumbersRequest() {
        }
        
        public SubtractTwoNumbersRequest(WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractTwoNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string y;
        
        public SubtractTwoNumbersRequestBody() {
        }
        
        public SubtractTwoNumbersRequestBody(string x, string y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractTwoNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersResponseBody Body;
        
        public SubtractTwoNumbersResponse() {
        }
        
        public SubtractTwoNumbersResponse(WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractTwoNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SubtractTwoNumbersResult;
        
        public SubtractTwoNumbersResponseBody() {
        }
        
        public SubtractTwoNumbersResponseBody(int SubtractTwoNumbersResult) {
            this.SubtractTwoNumbersResult = SubtractTwoNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Subtract2NumbersSoapChannel : WCFLabb1Client.Subtract2NumbersReference.Subtract2NumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Subtract2NumbersSoapClient : System.ServiceModel.ClientBase<WCFLabb1Client.Subtract2NumbersReference.Subtract2NumbersSoap>, WCFLabb1Client.Subtract2NumbersReference.Subtract2NumbersSoap {
        
        public Subtract2NumbersSoapClient() {
        }
        
        public Subtract2NumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Subtract2NumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Subtract2NumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Subtract2NumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersResponse WCFLabb1Client.Subtract2NumbersReference.Subtract2NumbersSoap.SubtractTwoNumbers(WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequest request) {
            return base.Channel.SubtractTwoNumbers(request);
        }
        
        public int SubtractTwoNumbers(string x, string y) {
            WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequest inValue = new WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequest();
            inValue.Body = new WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersResponse retVal = ((WCFLabb1Client.Subtract2NumbersReference.Subtract2NumbersSoap)(this)).SubtractTwoNumbers(inValue);
            return retVal.Body.SubtractTwoNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersResponse> WCFLabb1Client.Subtract2NumbersReference.Subtract2NumbersSoap.SubtractTwoNumbersAsync(WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequest request) {
            return base.Channel.SubtractTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersResponse> SubtractTwoNumbersAsync(string x, string y) {
            WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequest inValue = new WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequest();
            inValue.Body = new WCFLabb1Client.Subtract2NumbersReference.SubtractTwoNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((WCFLabb1Client.Subtract2NumbersReference.Subtract2NumbersSoap)(this)).SubtractTwoNumbersAsync(inValue);
        }
    }
}
