//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFLabb1Client.AddTwoNumbersReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddTwoNumbersReference.AddTwoNumbersSoap")]
    public interface AddTwoNumbersSoap {
        
        // CODEGEN: Generating message contract since element name x from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add2Numbers", ReplyAction="*")]
        WCFLabb1Client.AddTwoNumbersReference.Add2NumbersResponse Add2Numbers(WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add2Numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<WCFLabb1Client.AddTwoNumbersReference.Add2NumbersResponse> Add2NumbersAsync(WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add2NumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add2Numbers", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequestBody Body;
        
        public Add2NumbersRequest() {
        }
        
        public Add2NumbersRequest(WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add2NumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string y;
        
        public Add2NumbersRequestBody() {
        }
        
        public Add2NumbersRequestBody(string x, string y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add2NumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add2NumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.AddTwoNumbersReference.Add2NumbersResponseBody Body;
        
        public Add2NumbersResponse() {
        }
        
        public Add2NumbersResponse(WCFLabb1Client.AddTwoNumbersReference.Add2NumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add2NumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Add2NumbersResult;
        
        public Add2NumbersResponseBody() {
        }
        
        public Add2NumbersResponseBody(int Add2NumbersResult) {
            this.Add2NumbersResult = Add2NumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddTwoNumbersSoapChannel : WCFLabb1Client.AddTwoNumbersReference.AddTwoNumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddTwoNumbersSoapClient : System.ServiceModel.ClientBase<WCFLabb1Client.AddTwoNumbersReference.AddTwoNumbersSoap>, WCFLabb1Client.AddTwoNumbersReference.AddTwoNumbersSoap {
        
        public AddTwoNumbersSoapClient() {
        }
        
        public AddTwoNumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddTwoNumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoNumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoNumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFLabb1Client.AddTwoNumbersReference.Add2NumbersResponse WCFLabb1Client.AddTwoNumbersReference.AddTwoNumbersSoap.Add2Numbers(WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequest request) {
            return base.Channel.Add2Numbers(request);
        }
        
        public int Add2Numbers(string x, string y) {
            WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequest inValue = new WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequest();
            inValue.Body = new WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            WCFLabb1Client.AddTwoNumbersReference.Add2NumbersResponse retVal = ((WCFLabb1Client.AddTwoNumbersReference.AddTwoNumbersSoap)(this)).Add2Numbers(inValue);
            return retVal.Body.Add2NumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFLabb1Client.AddTwoNumbersReference.Add2NumbersResponse> WCFLabb1Client.AddTwoNumbersReference.AddTwoNumbersSoap.Add2NumbersAsync(WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequest request) {
            return base.Channel.Add2NumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFLabb1Client.AddTwoNumbersReference.Add2NumbersResponse> Add2NumbersAsync(string x, string y) {
            WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequest inValue = new WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequest();
            inValue.Body = new WCFLabb1Client.AddTwoNumbersReference.Add2NumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((WCFLabb1Client.AddTwoNumbersReference.AddTwoNumbersSoap)(this)).Add2NumbersAsync(inValue);
        }
    }
}
