//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFLabb1Client.Add3NumbersReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Add3NumbersReference.AddThreeNumbersSoap")]
    public interface AddThreeNumbersSoap {
        
        // CODEGEN: Generating message contract since element name x from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add3Numbers", ReplyAction="*")]
        WCFLabb1Client.Add3NumbersReference.Add3NumbersResponse Add3Numbers(WCFLabb1Client.Add3NumbersReference.Add3NumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add3Numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<WCFLabb1Client.Add3NumbersReference.Add3NumbersResponse> Add3NumbersAsync(WCFLabb1Client.Add3NumbersReference.Add3NumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add3NumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add3Numbers", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.Add3NumbersReference.Add3NumbersRequestBody Body;
        
        public Add3NumbersRequest() {
        }
        
        public Add3NumbersRequest(WCFLabb1Client.Add3NumbersReference.Add3NumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add3NumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string y;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string z;
        
        public Add3NumbersRequestBody() {
        }
        
        public Add3NumbersRequestBody(string x, string y, string z) {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add3NumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add3NumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.Add3NumbersReference.Add3NumbersResponseBody Body;
        
        public Add3NumbersResponse() {
        }
        
        public Add3NumbersResponse(WCFLabb1Client.Add3NumbersReference.Add3NumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add3NumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Add3NumbersResult;
        
        public Add3NumbersResponseBody() {
        }
        
        public Add3NumbersResponseBody(int Add3NumbersResult) {
            this.Add3NumbersResult = Add3NumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddThreeNumbersSoapChannel : WCFLabb1Client.Add3NumbersReference.AddThreeNumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddThreeNumbersSoapClient : System.ServiceModel.ClientBase<WCFLabb1Client.Add3NumbersReference.AddThreeNumbersSoap>, WCFLabb1Client.Add3NumbersReference.AddThreeNumbersSoap {
        
        public AddThreeNumbersSoapClient() {
        }
        
        public AddThreeNumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddThreeNumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddThreeNumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddThreeNumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFLabb1Client.Add3NumbersReference.Add3NumbersResponse WCFLabb1Client.Add3NumbersReference.AddThreeNumbersSoap.Add3Numbers(WCFLabb1Client.Add3NumbersReference.Add3NumbersRequest request) {
            return base.Channel.Add3Numbers(request);
        }
        
        public int Add3Numbers(string x, string y, string z) {
            WCFLabb1Client.Add3NumbersReference.Add3NumbersRequest inValue = new WCFLabb1Client.Add3NumbersReference.Add3NumbersRequest();
            inValue.Body = new WCFLabb1Client.Add3NumbersReference.Add3NumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.z = z;
            WCFLabb1Client.Add3NumbersReference.Add3NumbersResponse retVal = ((WCFLabb1Client.Add3NumbersReference.AddThreeNumbersSoap)(this)).Add3Numbers(inValue);
            return retVal.Body.Add3NumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFLabb1Client.Add3NumbersReference.Add3NumbersResponse> WCFLabb1Client.Add3NumbersReference.AddThreeNumbersSoap.Add3NumbersAsync(WCFLabb1Client.Add3NumbersReference.Add3NumbersRequest request) {
            return base.Channel.Add3NumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFLabb1Client.Add3NumbersReference.Add3NumbersResponse> Add3NumbersAsync(string x, string y, string z) {
            WCFLabb1Client.Add3NumbersReference.Add3NumbersRequest inValue = new WCFLabb1Client.Add3NumbersReference.Add3NumbersRequest();
            inValue.Body = new WCFLabb1Client.Add3NumbersReference.Add3NumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.z = z;
            return ((WCFLabb1Client.Add3NumbersReference.AddThreeNumbersSoap)(this)).Add3NumbersAsync(inValue);
        }
    }
}
