//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFLabb1Client.WeatherServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name WeatherForecastResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeatherForecast", ReplyAction="*")]
        WCFLabb1Client.WeatherServiceReference.WeatherForecastResponse WeatherForecast(WCFLabb1Client.WeatherServiceReference.WeatherForecastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeatherForecast", ReplyAction="*")]
        System.Threading.Tasks.Task<WCFLabb1Client.WeatherServiceReference.WeatherForecastResponse> WeatherForecastAsync(WCFLabb1Client.WeatherServiceReference.WeatherForecastRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeatherForecastRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeatherForecast", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.WeatherServiceReference.WeatherForecastRequestBody Body;
        
        public WeatherForecastRequest() {
        }
        
        public WeatherForecastRequest(WCFLabb1Client.WeatherServiceReference.WeatherForecastRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WeatherForecastRequestBody {
        
        public WeatherForecastRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeatherForecastResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeatherForecastResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFLabb1Client.WeatherServiceReference.WeatherForecastResponseBody Body;
        
        public WeatherForecastResponse() {
        }
        
        public WeatherForecastResponse(WCFLabb1Client.WeatherServiceReference.WeatherForecastResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WeatherForecastResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WeatherForecastResult;
        
        public WeatherForecastResponseBody() {
        }
        
        public WeatherForecastResponseBody(string WeatherForecastResult) {
            this.WeatherForecastResult = WeatherForecastResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WCFLabb1Client.WeatherServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WCFLabb1Client.WeatherServiceReference.WebService1Soap>, WCFLabb1Client.WeatherServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFLabb1Client.WeatherServiceReference.WeatherForecastResponse WCFLabb1Client.WeatherServiceReference.WebService1Soap.WeatherForecast(WCFLabb1Client.WeatherServiceReference.WeatherForecastRequest request) {
            return base.Channel.WeatherForecast(request);
        }
        
        public string WeatherForecast() {
            WCFLabb1Client.WeatherServiceReference.WeatherForecastRequest inValue = new WCFLabb1Client.WeatherServiceReference.WeatherForecastRequest();
            inValue.Body = new WCFLabb1Client.WeatherServiceReference.WeatherForecastRequestBody();
            WCFLabb1Client.WeatherServiceReference.WeatherForecastResponse retVal = ((WCFLabb1Client.WeatherServiceReference.WebService1Soap)(this)).WeatherForecast(inValue);
            return retVal.Body.WeatherForecastResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFLabb1Client.WeatherServiceReference.WeatherForecastResponse> WCFLabb1Client.WeatherServiceReference.WebService1Soap.WeatherForecastAsync(WCFLabb1Client.WeatherServiceReference.WeatherForecastRequest request) {
            return base.Channel.WeatherForecastAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFLabb1Client.WeatherServiceReference.WeatherForecastResponse> WeatherForecastAsync() {
            WCFLabb1Client.WeatherServiceReference.WeatherForecastRequest inValue = new WCFLabb1Client.WeatherServiceReference.WeatherForecastRequest();
            inValue.Body = new WCFLabb1Client.WeatherServiceReference.WeatherForecastRequestBody();
            return ((WCFLabb1Client.WeatherServiceReference.WebService1Soap)(this)).WeatherForecastAsync(inValue);
        }
    }
}
